//go:build ignore

// Generates compressible_ext.go from jshttp/mime-db.
//
// Usage: go run gen.go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"
)

const mimeDBURL = "https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json"

// MIME types to exclude even if mime-db marks them compressible
// (these typically wrap already-compressed or archive content, or are
// large binary blobs that are not useful to gzip).
var excludeMIMETypes = map[string]bool{
	"application/octet-stream": true,
	"application/x-tar":        true,
	// VM disk images / archives: huge binaries, often sparse or
	// internally compressed; .ova is itself a tar archive.
	"application/x-virtualbox-hdd":  true,
	"application/x-virtualbox-vdi":  true,
	"application/x-virtualbox-vhd":  true,
	"application/x-virtualbox-vmdk": true,
	"application/x-virtualbox-ova":  true,
	// Already-compressed image / texture formats.
	"image/vnd.ms-dds":          true, // DXT/BCn compressed texture
	"image/vnd.adobe.photoshop": true, // PSD has internal RLE/ZIP
}

// Extensions to exclude regardless of MIME type
// (some MIME types map to both compressed and uncompressed extensions).
var excludeExts = map[string]bool{
	"svgz": true, // pre-gzipped SVG
	"x3dz": true, // pre-gzipped X3D
}

// Extra extensions to always include (not all are covered by mime-db).
var extraExts = []string{
	"bin",
	// 3D Tiles
	"b3dm",
	"i3dm",
	"pnts",
	"cmpt",
	"subtree",
	// Cesium quantized-mesh terrain
	"terrain",
}

type entry struct {
	Compressible bool     `json:"compressible"`
	Extensions   []string `json:"extensions"`
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	resp, err := http.Get(mimeDBURL)
	if err != nil {
		return fmt.Errorf("fetch mime-db: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetch mime-db: status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read mime-db: %w", err)
	}

	var db map[string]entry
	if err := json.Unmarshal(body, &db); err != nil {
		return fmt.Errorf("parse mime-db: %w", err)
	}

	set := map[string]struct{}{}
	for mt, e := range db {
		if !e.Compressible || len(e.Extensions) == 0 {
			continue
		}
		if excludeMIMETypes[mt] {
			continue
		}
		for _, ext := range e.Extensions {
			ext = strings.ToLower(ext)
			if excludeExts[ext] {
				continue
			}
			set[ext] = struct{}{}
		}
	}
	for _, ext := range extraExts {
		set[strings.ToLower(ext)] = struct{}{}
	}

	exts := make([]string, 0, len(set))
	for ext := range set {
		exts = append(exts, ext)
	}
	sort.Strings(exts)

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by gen.go; DO NOT EDIT.")
	fmt.Fprintln(&buf, "// Source: https://github.com/jshttp/mime-db")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package main")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "// compressibleExts is the set of file extensions (without leading dot,")
	fmt.Fprintln(&buf, "// lowercased) whose contents benefit from gzip compression.")
	fmt.Fprintln(&buf, "var compressibleExts = map[string]bool{")
	for _, ext := range exts {
		fmt.Fprintf(&buf, "\t%q: true,\n", ext)
	}
	fmt.Fprintln(&buf, "}")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	if err := os.WriteFile("compressible_ext.go", src, 0644); err != nil {
		return fmt.Errorf("write: %w", err)
	}
	log.Printf("wrote compressible_ext.go (%d extensions)", len(exts))
	return nil
}
